# Generated by Django 6.0.1 on 2026-01-27 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('pharmacy', models.OneToOneField(blank=True, help_text='Linked pharmacy for pharmacy accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='pharmacies.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
