# Generated by Django 6.0.1 on 2026-02-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('medicine', 'Core Medicine'), ('skincare', 'Skincare'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby care'), ('vitamins', 'Vitamins & Supplements'), ('healthcare_devices', 'Home Healthcare Devices')], default='medicine', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PharmacyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('apollo', 'Apollo Pharmacy ERP'), ('wellness', 'Wellness Forever System'), ('custom', 'Custom API Integration')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='pharmacies.pharmacy')),
            ],
        ),
    ]
