# Generated by Django 5.2 on 2026-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_medicine_id_alter_pharmacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pharmacyintegration',
            name='system_type',
            field=models.CharField(choices=[('generic', 'Standard ERP (Local)'), ('multiloc', 'Cloud Multi-location System'), ('custom', 'Custom REST API Integration')], max_length=20),
        ),
    ]
