# Generated by Django 5.2 on 2026-02-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_stock_batch_number_stock_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='added_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_customers', to='pharmacies.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('extracted_text', models.TextField(blank=True, help_text='AI OCR Extracted text')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacies.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Same salt/composition', max_length=255)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives_suggested', to='pharmacies.medicine')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives_main', to='pharmacies.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'alternative')},
            },
        ),
    ]
